spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret:
            scope: read:user, user:email
            token-url: https://github.com/login/oauth/access_token
            redirect-url: http://localhost:8080/login/oauth2/code/github
      client-url: ${SPRING_CLIENT_URL:http://localhost:4000}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/autoShipDB}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
